---
apiVersion: batch/v1
kind: Job
metadata:
  name: devbox
  labels:
    kueue.x-k8s.io/queue-name: farai
spec:
  suspend: true
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: devbox
    spec:
      priorityClassName: interactive
      volumes:
        - name: working-storage
          persistentVolumeClaim:
            claimName: devbox-storage
      containers:
        - name: devbox-container
          image: ghcr.io/alignmentresearch/AmongUs:latest
          args: ["sleep", "2d"]
          resources:
            requests:
              cpu: 1
            limits:
              memory: "60G"
              nvidia.com/gpu: 1
          volumeMounts:
            - name: working-storage
              mountPath: /home/dev
          env:
            - name: GIT_ASKPASS
              value: "true"
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: pat
            - name: GIT_CONFIG_PARAMETERS
              value: "'credential.https://github.com.username=$(GITHUB_PAT)'"
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: api-key
            - name: WANDB_ENTITY
              value: "farai"
            - name: WANDB_PROJECT
              value: "AmongUs"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface
                  key: token
      imagePullSecrets:
        - name: docker
      restartPolicy: Never
